server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;

    # Essayer d'abord de trouver un fichier correspondant, sinon rediriger vers index.html
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Rediriger les erreurs 404 vers index.html pour les routes Angular
    error_page 404 /index.html;
}
 
